=pod

=encoding utf8

=head1 NAME

AN::Tools::Check

This module handles all types of system and internal checks.

=head1 SYNOPSIS

  use AN::Tools;

  # Get a common object handle on all AN::Tools::* modules.
  my $an = AN::Tools->new();
  
  # Check if a module is available for loading.
  $an->Check->error({
  	fatal		=>	1,
  	title		=>	"Something went boom",
  	message		=>	"Details on what went boom",
  	code		=>	<some integer representing what went boom>,
  	file		=>	$THIS_FILE,
  	line		=>	__LINE__
  });

=head1 DESCRIPTION

This module provides methods for checking various things, conditions and so forth.

=head1 NOTES

All AN::Tools::* modules expects the data they receive to be in UTF-8 encoded format. Likewise, they return UTF-8 encoded strings. If you are getting weird output or are seeing a "wide character in print" error, check that you are not getting double-encoded UTF-8 strings by casting your data as UTF-8 in the first place.

=head1 METHODS

Below are the detailed usage instructions for the methods provided by this module.

=head1 SEE ALSO

Other modules in the AN::Tools suite:

=over

=item AN::Tools

=item AN::Tools::Alert

=item AN::Tools::Log

=item AN::Tools::Math

=item AN::Tools::Readable

=item AN::Tools::String

=item AN::Tools::Storage

=back

=head1 LICENSE

 Copyright (c) 1997-2015 Alteeve's Niche! Inc., All rights reserved.
 This program is free software; you can redistribute it and/or modify it under the same terms as Perl itself.

=cut
