#!/usr/bin/perl
#
# AN!CDB - Alteeve's Niche! Cluster Dashboard
# 
# This software is released under the GNU GPL v2+ license.
# 
# No warranty is provided. Do not use this software unless you are willing and
# able to take full liability for it's use. The authors take care to prevent
# unexpected side effects when using this program. However, no software is
# perfect and bugs may exist which could lead to hangs or crashes in the
# program, in your cluster and possibly even data loss.
# 
# If you are concerned about these risks, please stick to command line tools.
# 
# This program is designed to extend clusters built according to this tutorial:
# - https://alteeve.com/w/2-Node_Red_Hat_KVM_Cluster_Tutorial
#
# This program's source code and updates are available on Github:
# - https://github.com/digimer/an-cdb
#
# Author;
# Alteeve's Niche!  -  https://alteeve.ca
# Madison Kelly     -  mkelly@alteeve.ca
# 
# TODO:
# - Adding a VM that is running on the "wrong" node gets it added to the wrong
#   failover domain.
# - Read and cache each cluster's /etc/hosts file.
# - Check to see if a VM is running outside of clustat and, if so, auto-enable
#   it on the appropriate node.
# - Add a "Cancel" button to each "Confirm" box.
# - Add an ability to trigger a status email. SIGUSR1 via script -> email
# - Allow users to rename VMs.
# - Add 'virsh undefine' when deleting VMs if 'virsh list --all' shows it still
#   defined on one of the VMs.
# - Build a VM outside of the cluster and sort out a way to have the dashboard
#   insert it into the cluster.
# - Make "Node -> Offline" be a "Warning!"
# - Make "Bond -> Down" be a warning
# - Enable an administrative LOCK OUT switch to prevent reboots during things
#   like firmware updates.
#   
# - Pass a timestamp with all CGI commands for five minutes in the future and
#   abort any actions that are older than that.

use strict;
use warnings;

my $THIS_FILE = "an-cdb";
require "./an-cluster.lib";
require "./an-cdb.lib";

# Turn off buffering so that the pinwheel will display while waiting
# for the SSH call(s) to complete.
$| = 1;

# Setup (sane) defaults
my $conf={
	nodes			=>	"",
	check_using_node	=>	"",
	up_nodes		=>	[],
	online_nodes		=>	[],
	path			=>	{
		'an-cdb_files'		=>	"/var/www/home",
		an_conf			=>	"/etc/an/an.conf",
		cat			=>	"/bin/cat",
		ccs			=>	"/usr/sbin/ccs",
		cluster_conf		=>	"/etc/cluster/cluster.conf",
		clusvcadm		=>	"/usr/sbin/clusvcadm",
		cp			=>	"/bin/cp",
		email_password_file	=>	"/var/www/tools/email_pw.txt",
		fence_ipmilan		=>	"/sbin/fence_ipmilan",
		gethostip		=>	"/bin/gethostip",
		'grep'			=>	"/bin/grep",
		guacamole_config	=>	"/etc/guacamole/noauth-config.xml",
		home			=>	"/var/www/home/",
		hostname		=>	"/bin/hostname",
		hosts			=>	"/etc/hosts",
		ifconfig		=>	"/sbin/ifconfig",
		'log'			=>	"/var/log/an-cdb.log",
		lvdisplay		=>	"/sbin/lvdisplay",
		ping			=>	"/usr/bin/ping",
		restart_tomcat		=>	"/var/www/tools/restart_tomcat6",
		ssh_config		=>	"/etc/ssh/ssh_config",
		virsh			=>	"/usr/bin/virsh",
	},
	handles			=>	{
		'log'			=>	"",
	},
	'system'		=>	{
		debug			=>	1,
		username		=>	getpwuid( $< ),
		config_read		=>	0,
		up_nodes		=>	0,
		online_nodes		=>	0,
		show_nodes		=>	0,
		footer_printed		=>	0,
		show_refresh		=>	1,
		root_password		=>	"",
		ignore_missing_vm	=>	0,
		#unusable_ram		=>	2147483648,	# 2 GiB
		unusable_ram		=>	3048259584,	# ~4 GiB, rounds to leave a clean number of GB on systems with mirrored memory.
		os_variant		=>	[
			"win7#!#Microsoft Windows 7",
			"vista#!#Microsoft Windows Vista",
			"winxp64#!#Microsoft Windows XP (x86_64)",
			"winxp#!#Microsoft Windows XP",
			"win2k#!#Microsoft Windows 2000",
			"win2k8#!#Microsoft Windows Server 2008",
			"win2k3#!#Microsoft Windows Server 2003",
			"openbsd4#!#OpenBSD 4.x",
			"freebsd8#!#FreeBSD 8.x",
			"freebsd7#!#FreeBSD 7.x",
			"freebsd6#!#FreeBSD 6.x",
			"solaris9#!#Sun Solaris 9",
			"solaris10#!#Sun Solaris 10",
			"opensolaris#!#Sun OpenSolaris",
			"netware6#!#Novell Netware 6",
			"netware5#!#Novell Netware 5",
			"netware4#!#Novell Netware 4",
			"msdos#!#MS-DOS",
			"generic#!#Generic",
			"debiansqueeze#!#Debian Squeeze",
			"debianlenny#!#Debian Lenny",
			"debianetch#!#Debian Etch",
			"fedora16#!#Fedora 16",
			"fedora15#!#Fedora 15",
			"fedora14#!#Fedora 14",
			"fedora13#!#Fedora 13",
			"fedora12#!#Fedora 12",
			"fedora11#!#Fedora 11",
			"fedora10#!#Fedora 10",
			"fedora9#!#Fedora 9",
			"fedora8#!#Fedora 8",
			"fedora7#!#Fedora 7",
			"fedora6#!#Fedora Core 6",
			"fedora5#!#Fedora Core 5",
			"mes5.1#!#Mandriva Enterprise Server 5.1 and later",
			"mes5#!#Mandriva Enterprise Server 5.0",
			"mandriva2010#!#Mandriva Linux 2010 and later",
			"mandriva2009#!#Mandriva Linux 2009 and earlier",
			"rhel7#!#Red Hat Enterprise Linux 7",
			"rhel6#!#Red Hat Enterprise Linux 6",
			"rhel5.4#!#Red Hat Enterprise Linux 5.4 or later",
			"rhel5#!#Red Hat Enterprise Linux 5",
			"rhel4#!#Red Hat Enterprise Linux 4",
			"rhel3#!#Red Hat Enterprise Linux 3",
			"rhel2.1#!#Red Hat Enterprise Linux 2.1",
			"sles11#!#Suse Linux Enterprise Server 11",
			"sles10#!#Suse Linux Enterprise Server",
			"ubuntuoneiric#!#Ubuntu 11.10 (Oneiric Ocelot)",
			"ubuntunatty#!#Ubuntu 11.04 (Natty Narwhal)",
			"ubuntumaverick#!#Ubuntu 10.10 (Maverick Meerkat)",
			"ubuntulucid#!#Ubuntu 10.04 (Lucid Lynx)",
			"ubuntukarmic#!#Ubuntu 9.10 (Karmic Koala)",
			"ubuntujaunty#!#Ubuntu 9.04 (Jaunty Jackalope)",
			"ubuntuintrepid#!#Ubuntu 8.10 (Intrepid Ibex)",
			"ubuntuhardy#!#Ubuntu 8.04 LTS (Hardy Heron)",
			"virtio26#!#Generic 2.6.25 or later kernel with virtio",
			"generic26#!#Generic 2.6.x kernel",
			"generic24#!#Generic 2.4.x kernel",
		],
	},
};

find_executables($conf);
read_hosts($conf);
read_ssh_config($conf);
read_conf($conf);

# I need to convert the global configuration of the clusters to the format I use here.
convert_cluster_config($conf);

# If there is only one cluster defined, use it. Note that I need a special
# exception in get_cgi_vars() for this to work properly.
if (not $conf->{cgi}{cluster})
{
	my @cluster_name;
	foreach my $cluster (keys %{$conf->{clusters}})
	{
		push @cluster_name, $cluster;
	}
	if (@cluster_name == 1)
	{
		$conf->{cgi}{cluster} = $cluster_name[0];
	}
}

# Get the CGI variables I might be passed.
get_cgi_vars($conf, [
	"adapter",
	"anvil",
	"boot_device",
	"change",
	"cluster",
	"config",
	"confirm",
	"cpu_cores",
	"device",
	"device_keys",
	"disk_address",
	"do",
	"driver_iso",
	"host",
	"ids",
	"insert",
	"install_iso",
	"logical_disk",
	"logo",
	"mail_data__to",
	"mail_data__sending_domain",
	"make_disk_good",
	"max_cores",
	"max_ram",
	"max_storage",
	"name",
	"node",
	"node_cluster_name",
	"os_variant",
	"ram",
	"ram_suffix",
	"row",
	"save",
	"section",
	"smtp__server",
	"smtp__port",
	"smtp__timeout",
	"smtp__username",
	"smtp__password",
	"smtp__helo_domain",
	"smtp__encrypt_pass",
	"smtp__security",
	"save",
	"storage",
	"target",
	"task",
	"vg_list",
	"vm",
	"vm_ram",
]);

# If the user is configuring the system, make sure no given Anvil! is selected.
if ($conf->{cgi}{config})
{
	$conf->{cgi}{cluster} = "";
}

# If 'anvil' was passed, get it's ID and then check for CGI variables.
if (($conf->{cgi}{save}) && ($conf->{cgi}{anvil}))
{
	my $this_cluster = $conf->{cgi}{anvil};
	if ($conf->{clusters}{$this_cluster}{id})
	{
		my $this_id = $conf->{clusters}{$this_cluster}{id};
		get_cgi_vars($conf, [
			"cluster__${this_id}__name",
			"cluster__${this_id}__description",
			"cluster__${this_id}__url",
			"cluster__${this_id}__company",
			"cluster__${this_id}__ricci_pw",
			"cluster__${this_id}__root_pw",
			"cluster__${this_id}__nodes_1_name",
			"cluster__${this_id}__nodes_1_ip",
			"cluster__${this_id}__nodes_1_port",
			"cluster__${this_id}__nodes_2_name",
			"cluster__${this_id}__nodes_2_ip",
			"cluster__${this_id}__nodes_2_port",
			"cluster__${this_id}__smtp__server",
			"cluster__${this_id}__smtp__port",
			"cluster__${this_id}__smtp__timeout",
			"cluster__${this_id}__smtp__username",
			"cluster__${this_id}__smtp__password",
			"cluster__${this_id}__smtp__security",
			"cluster__${this_id}__smtp__encrypt_pass",
			"cluster__${this_id}__smtp__helo_domain",
			"cluster__${this_id}__mail_data__to",
			"cluster__${this_id}__mail_data__sending_domain",
		]);
	}
}

# Pick up the list of volume groups.
if ($conf->{cgi}{vg_list})
{
	my @more_vars;
	foreach my $vg (split/,/, $conf->{cgi}{vg_list})
	{
		next if not $vg;
		push @more_vars, "vg_$vg";
		push @more_vars, "vg_suffix_$vg";
	}
	get_cgi_vars($conf, \@more_vars);
}
# Pick up the list of optical devices.
if ($conf->{cgi}{device_keys})
{
	my @more_vars;
	foreach my $device (split/,/, $conf->{cgi}{device_keys})
	{
		next if not $device;
		push @more_vars, "$device";
		my $drive = ($device =~ /media_(.*)/)[0];
		push @more_vars, "insert_$drive";
	}
	get_cgi_vars($conf, \@more_vars);
}

header($conf, "AN!CDB", "Cluster Dashboard", "logo_an-cdb_02.png");

# Do I have a cluster name?
if ($conf->{cgi}{logo})
{
	if ($conf->{cgi}{config})
	{
		configure_dashboard($conf);
	}
	else
	{
		ask_which_cluster($conf);
	}
}
elsif ($conf->{cgi}{config})
{
	configure_dashboard($conf);
}
elsif ($conf->{cgi}{cluster})
{
	my $cluster = $conf->{cgi}{cluster};
	$conf->{'system'}{root_password} = $conf->{clusters}{$cluster}{root_pw};
	#record($conf, "$THIS_FILE ".__LINE__."; cluster: [$cluster], clusters::${cluster}::root_pw: [$conf->{clusters}{$cluster}{root_pw}], system::root_password: [$conf->{'system'}{root_password}]\n");
	
	# If the requested cluster isn't found in the config file, error out.
	if (not $conf->{clusters}{$cluster}{nodes})
	{
		print "
<table align=\"center\">
	<tr>
		<td colspan=\"3\">
			<b>Please choose an <i>Anvil!</i></b>
		</td>
	</tr>
	<tr>
		<td class=\"highlight_bad\">
			Unknown
		</td>
		<td>
			<br />
			I am sorry, but I can not find a cluster called <span class=\"fixed_width\">$cluster</span> in the configuration file.<br />
			<br />
			Please update <span class=\"fixed_width\">/etc/an/an.conf</span> in order to add a new cluster to this dashboard server.<br />
			<br />
		</td>
	</tr>
</table>
<br />
";
	}
	else
	{
		if ($conf->{cgi}{task})
		{
			$conf->{'system'}{show_refresh} = 0;
			process_task($conf);
		}
		else
		{
			# Set the node list.
			#record($conf, "cluster: [$cluster], ricci_pw: [$conf->{clusters}{$cluster}{ricci_pw}]\n");
			$conf->{nodes} = $conf->{clusters}{$cluster}{nodes};
			scan_cluster($conf);
			display_details($conf);
		}
	}
}
else
{
	# Ask the user which cluster they want to look at.
	ask_which_cluster($conf);
}
footer($conf);

exit (0);
