#!/usr/bin/perl
# 
# AN!MediaConnector
# 
# This allows a mechanism for taking a CD or DVD, turning it into an ISO and
# pushing it to a cluster's /shared/files/ directory. It also allows for 
# connecting and disconnecting these ISOs to and from VMs.
# 
# TODO: Merge this into the main program.
#       

use strict;
use warnings;

my $THIS_FILE = "an-mc";
require "./common.lib";
require "./an-cluster.lib";
require "./an-mc.lib";

# Turn off buffering so that the pinwheel will display while waiting
# for the SSH call(s) to complete.
$| = 1;

my ($conf) = initialize($THIS_FILE);
# 
# # Remember to keep 'create_image_and_upload.pl' updated.
# my $conf={
# 	path			=>	{
# 		an_conf			=>	"/etc/an/an.conf",
# 		check_dvd		=>	"/var/www/tools/check_dvd",
# 		do_dd			=>	"/var/www/tools/do_dd",
# 		hostname		=>	"/bin/hostname",
# 		hosts			=>	"/etc/hosts",
# 		'log'			=>	"/var/log/an-cdb.log",
# 		media			=>	"/var/www/home/media/",
# 		rsync			=>	"/usr/bin/rsync",
# 		screen			=>	"/usr/bin/screen",
# 		shared			=>	"/shared/files/",	# This is hard-coded in the file delete function.
# 		status			=>	"/var/www/home/status/",
# 	},
# 	args			=>	{
# 		check_dvd		=>	"--dvd --no-cddb --no-device-info --no-disc-mode --no-vcd",
# 		rsync			=>	"-av --partial",
# 	},
# 	'system'		=>	{
# 		dd_block_size		=>	"1M",
# 	},
# };

find_executables($conf);
read_hosts($conf);
read_ssh_config($conf);
read_conf($conf);

# I need to convert the global configuration of the clusters to the format I use here.
convert_cluster_config($conf);

# If there is only one cluster defined, use it. Note that I need a special
# exception in get_cgi_vars() for this to work properly.
if (not $conf->{cgi}{cluster})
{
	my @cluster_name;
	foreach my $cluster (keys %{$conf->{clusters}})
	{
		push @cluster_name, $cluster;
	}
	if (@cluster_name == 1)
	{
		$conf->{cgi}{cluster} = $cluster_name[0];
	}
}

get_cgi_vars($conf, [
	"cluster",
	"confirm",
	"dev",
	"file",
	"name",
	"task",
	"url",
]);

# Print the header.
header($conf);

# Do I have a cluster name?
#record($conf, "$THIS_FILE ".__LINE__."; cgi::cluster: [$conf->{cgi}{cluster}]\n");
if ($conf->{cgi}{cluster})
{
	my $cluster                      = $conf->{cgi}{cluster};
	$conf->{'system'}{root_password} = $conf->{clusters}{$cluster}{root_pw};
	$conf->{nodes}                   = $conf->{clusters}{$cluster}{nodes};
	#record($conf, "$THIS_FILE ".__LINE__."; nodes: [$conf->{nodes}], task: [$conf->{cgi}{task}], system::root_password: [$conf->{'system'}{root_password}]\n");
	if ($conf->{cgi}{task})
	{
		$conf->{'system'}{show_refresh} = 0;
		process_task($conf);
	}
	else
	{
		# Set the node list.
		read_shared($conf);
	}
}
else
{
	# Ask the user which cluster they want to look at.
	ask_which_cluster($conf);
}
footer($conf);


exit 0;
