#!/usr/bin/perl
# 
# AN!CM - Cluster Monitor
# 
# This program watches the hardware and cluster stack for changes, sending
# alert emails when needed.
# 

use strict;
use warnings;
require "./an-cm.lib";
our $THIS_FILE = "an-cm";

$SIG{INT}  = \&catch_sig;
$SIG{TERM} = \&catch_sig;

my $conf = {
	cluster		=>	{
# 		name			=>	"pp-cluster-01",
# 		description		=>	"Plastic Plus \"Cluster 01\"",
# 		nodes			=>	["pp-c01n01", "pp-c01n02"],
# 		company			=>	"CC Systems",

# 		name			=>	"cc-cluster-02",
# 		description		=>	"CC Systems \"Cluster 02\" in Oakville",
# 		nodes			=>	["cc-c02n01", "cc-c02n02"],
# 		company			=>	"CC Systems",
		
		name			=>	"an-cluster-01",
		description		=>	"Alteeve's Niche! \"Cluster 01\" (in Oakville)",
		nodes			=>	["an-c01n01", "an-c01n02"],
		company			=>	"Alteeve's Niche!",
	},
	node		=>	{
		me			=>	{
			long_name		=>	"",
			short_name		=>	"",
		},
		peer			=>	{
			long_name		=>	"",
			short_name		=>	"",
		},
	},
	smtp			=>	{
		server			=>	"mail.alteeve.ca",
		port			=>	587,
		timeout			=>	60,
		username		=>	"clusters\@alteeve.ca",
		password		=>	"file:./email_pw.txt",
		security		=>	"STARTTLS",
		encrypt_pass		=>	1,
		helo_domain		=>	"alteeve.ca",
	},
	mail_data		=>	{
		to			=>	"alert\@alteeve.ca",
		sending_domain		=>	"mail.alteeve.ca",
		subject			=>	"test",
		body			=>	"test",
	},
	handles			=>	{
		'log'			=>	"",
	},
	path			=>	{
		'log'			=>	"/var/log/an-cm.log",
		uname			=>	"/bin/uname",
		clustat			=>	"/usr/sbin/clustat",
		pgrep			=>	"/usr/bin/pgrep",
		ifconfig		=>	"/sbin/ifconfig",
		brctl			=>	"/usr/sbin/brctl",
		MegaCli64		=>	"/opt/MegaRAID/MegaCli/MegaCli64",
		ipmitool		=>	"/usr/bin/ipmitool",
	},
	alerts			=>	{
		storage			=>	{
			delta			=>	10,	# A change of this amoint between scans will trigger an email. Factor the 'sleep_time' below.
			upper_threshold		=>	40,	# A temperature above this will trigger an alert. Set according to the drive specs! (55c max for Seagate 15krpm)
			power_down_threshold	=>	50,	# A temperature above this will trigger a complete shutdown of the server. Be sure to reference the OEM specs and leave enough of a buffer to give the machine time to shutdown before passing the maximum temp.
		},
	},
	'system'		=>	{
		sleep_time		=>	10,
		storage_type		=>	"",
		ipmi_available		=>	1,
		cluster_running		=>	1,
		warning_event		=>	0,		# This is set true when a serious event has occured.
		critical_event		=>	0,		# This is set true when an alert is critical.
		emergency_shutdown	=>	0,		# This is set true when a significant fault has been detected requiring an automated shutdown of the cluster.
		disable_emergency_shutdown	=>	0,	# The client must *physically sign* that they wish to disable automated shutdown. Enabling this option removed the ability for the node to power off to avoid physical damage. ENABLING THIS OPTION WILL VOID THE HARDWARE WARRANTY IF UPPER THRESHOLDS ARE EXCEEDED!
		migration_target	=>	1,		# This is set true when a warning has been triggered. This prevents the other node from trying to migrate VMs to this node in case it is suffering similar environmental problems. This is cleared only when a clean scan has completed.
	},
};

avoid_duplicate_run($conf);
get_hostname($conf);
$conf->{mail_data}{subject_prefix} = "[ AN-CM ] - $conf->{cluster}{company} - $conf->{cluster}{name} - $conf->{node}{me}{short_name}";
$conf->{mail_data}{body_suffix}    = "
--[ Source Details ]--------------------------------------------------
Company: $conf->{cluster}{company}
Cluster: $conf->{cluster}{name}
Node:    $conf->{node}{me}{long_name}
Description:
 - $conf->{cluster}{description}

If you have any questions or concerns, please don't hesitate to
contact support. 

                    https://alteeve.com/w/Support

                                                     Alteeve's Niche!
                                                      Cluster Monitor
----------------------------------------------------------------------
--
You received this email because you were listed as a contact for the
AN!Cluster described in this email. If you do not wish to receives
these emails, please contact your systems administrator. AN!CM runs on
cluster nodes directly, and are not sent by Alteeve's Niche!. If you
do not know who controls these servers, please visit the support link
above and we will try to help you identify the person who can assist
you.
";
read_states($conf);
initial_report($conf);

# Infinite loop time
while (1)
{
	#record($conf, "$THIS_FILE ".__LINE__."; Checking for changes.\n");
	check_for_changes($conf);
	sleep $conf->{'system'}{sleep_time};
}

exit(0);



# This catches SIGINT and SIGTERM and fires out an email before shutting down.
sub catch_sig
{
	my $signame = shift;
	
	$conf->{mail_data}{subject} = "Cluster Monitor Shutdown";
	$conf->{mail_data}{body}    = "
The $conf->{node}{me}{short_name} cluster node's monitor program has stopped.
It received a SIG${signame} signal and shut down.
";
	send_email($conf);
	
	die "Process with PID $$ Exiting on SIG${signame}.\n";
}
