#!/usr/bin/perl
#
# This generates the kickstart files for the RHEL and CentOS ISOs used by the Anvil! HA Platform m2.
# 
# TODO: Adapt this to run from anvil-generate-iso so that users can further customize their installs.
# 

use strict;
use warnings;

my $conf = {
	ks	=>	{
		centos	=>	{
			dvd	=>	{
				striker	=>	{
					1	=>	{
						contents	=>	"",
						file_name	=>	"",
					},
					2	=>	{
						contents	=>	"",
						file_name	=>	"",
					},
				},
			},
			pxe	=>	{
				striker	=>	{
					1	=>	{
						contents	=>	"",
						file_name	=>	"",
					},
					2	=>	{
						contents	=>	"",
						file_name	=>	"",
					},
				},
				node	=>	{
					1	=>	{
						source	=>	{
							1	=>	{
								contents	=>	"",
								file_name	=>	"",
							},
							2	=>	{
								contents	=>	"",
								file_name	=>	"",
							},
						},
					},
					2	=>	{
						source	=>	{
							1	=>	{
								contents	=>	"",
								file_name	=>	"",
							},
							2	=>	{
								contents	=>	"",
								file_name	=>	"",
							},
						},
					},
				},
			},
			usb	=>	{
				striker	=>	{
					1	=>	{
						contents	=>	"",
						file_name	=>	"",
					},
					2	=>	{
						contents	=>	"",
						file_name	=>	"",
					},
				},
			},
		},
		rhel	=>	{
			dvd	=>	{
				striker	=>	{
					1	=>	{
						contents	=>	"",
						file_name	=>	"",
					},
					2	=>	{
						contents	=>	"",
						file_name	=>	"",
					},
				},
			},
			pxe	=>	{
				striker	=>	{
					1	=>	{
						contents	=>	"",
						file_name	=>	"",
					},
					2	=>	{
						contents	=>	"",
						file_name	=>	"",
					},
				},
				node	=>	{
					1	=>	{
						source	=>	{
							1	=>	{
								contents	=>	"",
								file_name	=>	"",
							},
							2	=>	{
								contents	=>	"",
								file_name	=>	"",
							},
						},
					},
					2	=>	{
						source	=>	{
							1	=>	{
								contents	=>	"",
								file_name	=>	"",
							},
							2	=>	{
								contents	=>	"",
								file_name	=>	"",
							},
						},
					},
				},
			},
			usb	=>	{
				striker	=>	{
					1	=>	{
						contents	=>	"",
						file_name	=>	"",
					},
					2	=>	{
						contents	=>	"",
						file_name	=>	"",
					},
				},
			},
		},
	},
	sys	=>	{
		admin_user	=>	"admin",
		anvil_name	=>	"Anvil!",
		background	=>	"splash.jpg",
		bcn_netmask	=>	"16",
		company_name	=>	"Alteeve's Niche!",
		domain		=>	"alteeve.ca",
		ifn_dns1	=>	"8.8.8.8",
		ifn_dns2	=>	"8.8.4.4",
		ifn_gateway	=>	"10.255.255.254",
		ifn_netmask	=>	"16",
		keyboard	=>	"us",
		language	=>	"en_CA.UTF-8",
		os_version	=>	"6.8",
		output_dir	=>	"/data0/ISO/Anvil-m2/",
		password	=>	"Initial1",	# User and 'root'.
		prefix		=>	"an",
		striker_bcn	=>	"10.20.4",
		striker_ifn	=>	"10.255.4",
		striker_name	=>	"Striker",
		timezone	=>	"America/Toronto",
	},
};

print get_date($conf);

print "Generating Anvil! kickstart scripts\n";

foreach my $distro (sort {$a cmp $b} keys %{$conf->{ks}})
{
	print "- Distro: [$distro]\n";
	my $directory = "$conf->{sys}{output_dir}/$distro/$conf->{sys}{os_version}/Anvil/ks";
	if (not -e $directory)
	{
		mkdir $directory or die "Failed to create: [$directory], error: $!\n";
	}
	foreach my $target (sort {$a cmp $b} keys %{$conf->{ks}{$distro}})
	{
		foreach my $machine (sort {$a cmp $b} keys %{$conf->{ks}{$distro}{$target}})
		{
			foreach my $number (sort {$a cmp $b} keys %{$conf->{ks}{$distro}{$target}{$machine}})
			{
				if ($machine eq "node")
				{
					# Nodes have two sources; PXE from striker 1 or 2.
					foreach my $source (1..2)
					{
						$conf->{ks}{$distro}{$target}{$machine}{$number}{source}{$source}{file_name} = "pxe-new-node0${number}_from-striker0${source}.ks";
						$conf->{ks}{$distro}{$target}{$machine}{$number}{source}{$source}{contents}  = generate_ks($conf, $distro, $target, $machine, $number, $source);
						my $shell_call = "$directory/$conf->{ks}{$distro}{$target}{$machine}{$number}{source}{$source}{file_name}";
						open (my $file_handle, ">$shell_call") or die "Failed to write: [$shell_call], error: $!\n";
						print $file_handle $conf->{ks}{$distro}{$target}{$machine}{$number}{source}{$source}{contents};
						close $file_handle;
						print "  - Wrote: [$shell_call]\n";
					}
				}
				else
				{
					$conf->{ks}{$distro}{$target}{$machine}{$number}{file_name} = "${target}-new-${machine}0${number}.ks";
					$conf->{ks}{$distro}{$target}{$machine}{$number}{contents}  = generate_ks($conf, $distro, $target, $machine, $number, 0);
					my $shell_call = "$directory/$conf->{ks}{$distro}{$target}{$machine}{$number}{file_name}";
					open (my $file_handle, ">$shell_call") or die "Failed to write: [$shell_call], error: $!\n";
					print $file_handle $conf->{ks}{$distro}{$target}{$machine}{$number}{contents};
					close $file_handle;
					print "  - Wrote: [$shell_call]\n";
				}
			}
		}
	}
}

sub generate_ks
{
	my ($conf, $distro, $target, $machine, $number, $source) = @_;
	
	my $say_os         = $distro eq "centos" ? "CentOS" : "RHEL";
	my $say_ver        = $conf->{sys}{os_version};
	my $os_dir         = $distro eq "centos" ? "centos6" : "rhel6";
	my $say_target     = $target eq "pxe" ? "Network Install (PXE)" : 
			     $target eq "dvd" ? "Optical Media (DVD)" : 
			     "USB Drive";
	my $say_machine    = $machine eq "striker" ? "$conf->{sys}{striker_name} Dashboard" : "$conf->{sys}{anvil_name} Node";
	   $say_machine   .= " #0".$number;
	my $peer_number    = $number eq "1" ? 2 : 1;
	my $hostname       = "new-${machine}0${number}";
	my $striker_bcn    = $conf->{sys}{striker_bcn};
	my $striker_ifn    = $conf->{sys}{striker_ifn};
	my $admin_user     = $conf->{sys}{admin_user};
	my $password       = $conf->{sys}{password};
	my $timezone       = $conf->{sys}{timezone};
	my $language       = $conf->{sys}{language};
	my $domain         = $conf->{sys}{domain};
	my $peer_ip        = $number eq "1" ? "$striker_bcn.2" : "$striker_bcn.1";
	my $my_bcn_ip      = $number eq "1" ? "$striker_bcn.1" : "$striker_bcn.2";
	my $my_ifn_ip      = $number eq "1" ? "$striker_ifn.1" : "$striker_ifn.2";
	my $dhcp_range     = $number eq "1" ? "10.20.10.200:10.20.10.209" : "10.20.10.210:10.20.10.219";
	my $keyboard       = $conf->{sys}{keyboard};
	my $selinux        = $machine eq "striker" ? "permissive" : "enforcing";
	my $packages       = get_packages($conf, $machine, $distro);
	my $iso_name       = "Anvil_m2_${say_os}-${say_ver}_alpha.iso";
	my $background     = $conf->{sys}{background};
	my $bcn_netmask    = $conf->{sys}{bcn_netmask};
	my $ifn_netmask    = $conf->{sys}{ifn_netmask};
	my $ifn_gateway    = $conf->{sys}{ifn_gateway};
	my $ifn_dns1       = $conf->{sys}{ifn_dns1};
	my $ifn_dns2       = $conf->{sys}{ifn_dns2};
	my $prefix         = $conf->{sys}{prefix};
	my $anvil_name     = $conf->{sys}{anvil_name};
	my $striker_name   = $conf->{sys}{striker_name};
	my $company_name   = $conf->{sys}{company_name};
	my $common_post    = get_common_post($conf);
	my $copy_logs      = get_copy_logs($conf);
	
	# (De)branding doesn't apply to the kickstart comment header.
	my $content = "### Alteeve's Niche! Inc. - Anvil! High Availability Platform
# License: GPLv2
# Built:   ".get_date($conf)."
# Target:  $say_target
# OS:      $say_os
# Machine: $say_machine

### Setup values.
# Run a text-based install
install
text
";
	if ($target eq "pxe")
	{
		# If it's a dashboard, install from the peer. If it's a node, install from the source.
		if ($machine eq "node")
		{
			$content .= "
# Installing from $striker_name 0${source}'s PXE server.
url --url=http://$striker_bcn.${source}/$os_dir/x86_64/img/
";
		}
		else
		{
			$content .= "
# Installing from $striker_name 0${number}'s PXE server.
url --url=http://$peer_ip/$os_dir/x86_64/img/
";
		}
	}
	elsif ($target eq "dvd")
	{
		$content .= "
# Installing from DVD.
cdrom
";
	}
	else
	{
		$content .= "
# Installing from USB, no argument needed.
";
	}
	
	$content .= "
# Set the language and keyboard type.
lang $language
keyboard $keyboard

# Set the system clock to UTC and then define the timezone.
timezone --utc $timezone

# This sets the (first) ethernet device. There is currently no way to map
# device names to physical interfaces. For this reason, we use DHCP for install
# and configure the network manually post-install.
network --device eth0 --bootproto dhcp --onboot yes --hostname $hostname.$domain

# This is the root user's password. The one below should be taken as an example
# and changed as it is a terrible password.
authconfig --enableshadow --passalgo=sha512 --enablefingerprint
rootpw $password

# Default admin user account.
user --name=$admin_user --plaintext --password=$password

# At this time, $striker_name does not yet work with SELinux in enforcing mode. This
# is expected to change in a (near) future release.
firewall --service=ssh
selinux --$selinux

# There is no need for the 'first boot' menu system to run, so we will disable
# it.
firstboot --disable

# Set the installation logging level.
logging --level=debug

# Enable httpd so that the local repo is available on boot.
services --enabled httpd,gpm,iptables
services --disabled kdump

# Reboot when the install is finished.
reboot

# This runs a script (below) that generates the partitioning information
# depending on a rudamentary test for available storage devices.
\%include /tmp/part-include

$packages
";
	
	# From here, it starts to depend a lot on what we're building the KS for.
	if ($machine eq "node")
	{
		# Nodes are easier because they're only ever PXE.
		$content .= "
# Now it's time for the first chroot'ed configuration steps.
\%post --log=/tmp/post-install_chroot.log

$common_post

# Download 'list-ips' from the Striker we're installing from.
echo \"Downloading 'list-ips'.\"
mkdir /sbin/striker
curl http://${striker_bcn}.${source}/$os_dir/x86_64/img/Striker/striker-master/tools/list-ips > /sbin/striker/list-ips
chown root:root /sbin/striker/list-ips
chmod 755 /sbin/striker/list-ips

# Download 'fence_raritan_snmp' from the Striker we're installing from.
echo \"Downloading 'fence_raritan_snmp'.\"
curl http://${striker_bcn}.${source}/$os_dir/x86_64/img/Tools/fence/fence_raritan_snmp > /usr/sbin/fence_raritan_snmp
chown root:root /usr/sbin/fence_raritan_snmp
chmod 755 /usr/sbin/fence_raritan_snmp

# Download 'anvil-map-network' from the Striker we're installing from.
echo \"Downloading 'anvil-map-network'.\"
curl http://${striker_bcn}.${source}/$os_dir/x86_64/img/Striker/striker-master/tools/anvil-map-network > /sbin/striker/anvil-map-network
chown root:root /sbin/striker/hap-map-network
chmod 755 /sbin/striker/anvil-map-network

### TEMPORARY (Remove once https://bugzilla.redhat.com/show_bug.cgi?id=1285921 has a new resource-agents RPM).
echo \"Downloading 'vm.sh'.\"
curl http://${striker_bcn}.${source}/$os_dir/x86_64/img/Tools/vm.sh > /root/vm.sh
chown root:root /root/vm.sh
chmod 755 /root/vm.sh

# Show details on boot.
echo \"Setting plymouth to use detailed boot screen\"
plymouth-set-default-theme details --rebuild-initrd
sed -i 's/ rhgb//'  /boot/grub/grub.conf
sed -i 's/ quiet//' /boot/grub/grub.conf

# Setup the Striker repos.
cat > /etc/yum.repos.d/striker01.repo << EOF
[striker01]
name=$striker_name 01 Repository
baseurl=http://${striker_bcn}.1/$os_dir/x86_64/img/
enabled=1
gpgcheck=0
skip_if_unavailable=1
priority=1
EOF

cat > /etc/yum.repos.d/striker02.repo << EOF
[striker02]
name=$striker_name 02 Repository
baseurl=http://${striker_bcn}.2/$os_dir/x86_64/img/
enabled=1
gpgcheck=0
skip_if_unavailable=1
priority=1
EOF
\%end

$copy_logs

### Script to setup partitions.
\%pre --log=/tmp/ks-preinstall.log

#!/bin/sh

# Prepare the disks in the script below. It checks '/proc/partitions' to see
# what configuration to use. 

###############################################################################
# Below is for 40 GiB / partitions with the balance of free space to be       #
# configured later.                                                           #
###############################################################################

# Default is to use /dev/sda. At this time, software arrays are not supported.
DRIVE=\"sda\";

# /dev/vda KVM virtual machine
if grep -q vda /proc/partitions
then
	DRIVE=\"vda\"
fi

# Zero-out the first 100GB to help avoid running into problems when a node that
# was previously in a cluster gets rebuilt. Only run on real hardware, tends to
# crash VMs.
if grep -q sda /proc/partitions;
then
	echo \"Please be patient! Zero'ing out the first 100 GiB of /dev/\${DRIVE}...\"
	dd if=/dev/zero of=/dev/\${DRIVE} bs=1G count=100
fi

### Make sure we always create a GPT disk (https://access.redhat.com/solutions/55652)
echo \"Creating a GPT disk label\"
/usr/bin/dd bs=512 count=10 if=/dev/zero of=/dev/\${DRIVE}
/usr/sbin/parted --script /dev/\${DRIVE} mklabel gpt
/usr/sbin/parted -l /dev/\${DRIVE}
/usr/bin/sleep  30

# Now write the partition script
echo \"Done! Now creating and formatting partitions.\"
cat > /tmp/part-include <<END

zerombr
clearpart --all --drives=\${DRIVE}
ignoredisk --only-use=\${DRIVE}
bootloader --location=mbr --driveorder=\${DRIVE}

part     /boot --fstype ext4 --size=512   --asprimary --ondisk=\${DRIVE}
part     swap  --fstype swap --size=4096  --asprimary --ondisk=\${DRIVE}
part     /     --fstype ext4 --size=40960 --asprimary --ondisk=\${DRIVE}

END

\%end
";
	}
	else
	{
		# Regardless of the install type, 
		$content .= "
# First non-chroot steps
\%post --nochroot --log=/tmp/nochroot-post-install.log
#!/bin/bash

# Create the install repo and PXE boot directories.
echo 'Creating the apache docroot and PXE directories.'

# Apache directories
mkdir -p /mnt/sysimage/var/www/html/$os_dir/x86_64/{img,iso,ks,files}

# PXE/tftp directories
mkdir -p /mnt/sysimage/var/lib/tftpboot/boot/$os_dir/x86_64/
mkdir /mnt/sysimage/var/lib/tftpboot/pxelinux.cfg

# Create the source mount point.
mkdir /mnt/source;
";
		# Where we get the source ISO depends entirely on how this install is running.
		if ($target eq "pxe")
		{
			# PXE target
			$content .= "
# Download the ISO and mount it.
echo 'Downloading the source ISO and mounting it'
wget http://$peer_ip/$os_dir/x86_64/iso/$iso_name -O /mnt/sysimage/var/www/html/$os_dir/x86_64/iso/$iso_name

# Make sure our source is mounted.
mount -o loop /mnt/sysimage/var/www/html/$os_dir/x86_64/iso/$iso_name /mnt/source/
";
		}
		elsif ($target eq "dvd")
		{
			# DVD/ISO target
			$content .= "
# Make sure the optical drive is mounted.
mount /dev/cdrom /mnt/source;

# Create a copy of the install ISO on $striker_name.
echo 'Copying the install iso image using dd. Be patient'
dd if=/dev/cdrom of=/mnt/sysimage/var/www/html/$os_dir/x86_64/iso/$iso_name
";
		}
		else
		{
			# USB target
			$content .= "
# Make sure our USB source partition is mounted.
mount /dev/sdb1 /mnt/source;

# Copy the install ISO into place
echo 'Copying the install iso image. Be patient'
cp -v /mnt/source/*.iso /mnt/sysimage/var/www/html/$os_dir/x86_64/iso/
";
		}
		
		# Now the common bits.
		$content .= "

# Setup 'list-ips'.
echo \"Setting up 'list-ips'.\"
mkdir /mnt/sysimage/sbin/striker
cp /mnt/source/Striker/striker-master/tools/list-ips /mnt/sysimage/sbin/striker/list-ips
chown root:root /sbin/striker/list-ips
chmod 755 /sbin/striker/list-ips

# Copy the raritan fence agent into place.
echo 'Copying fence_raritan_snmp into /usr/sbin/'
cp /mnt/source/Tools/fence/fence_raritan_snmp /mnt/sysimage/usr/sbin/

# Copy the node and dashboard KSes into place
echo 'Copying the KS scripts into place.'
cp /mnt/source/ks/pxe-new-node01_from-striker0${number}.ks /mnt/sysimage/var/www/html/$os_dir/x86_64/ks/pxe-new-node01.ks
cp /mnt/source/ks/pxe-new-node02_from-striker0${number}.ks /mnt/sysimage/var/www/html/$os_dir/x86_64/ks/pxe-new-node02.ks
cp /mnt/source/ks/pxe-new-striker01.ks             /mnt/sysimage/var/www/html/$os_dir/x86_64/ks/
cp /mnt/source/ks/pxe-new-striker02.ks             /mnt/sysimage/var/www/html/$os_dir/x86_64/ks/

# A little flair...
echo 'Setting the PXE wallpaper.'
cp /mnt/source/syslinux/$background /mnt/sysimage/var/lib/tftpboot/

# Copy the $striker_name source files and installer into place
echo 'Copying the $striker_name installer and source code into place.'
cp      /mnt/source/$conf->{sys}{striker_name}/master.zip                             /mnt/sysimage/root/
cp -Rvp /mnt/source/$conf->{sys}{striker_name}/striker-master                         /mnt/sysimage/root/
cp      /mnt/source/$conf->{sys}{striker_name}/striker-master/tools/striker-installer /mnt/sysimage/root/

echo \"Copying 'Tools' into /mnt/sysimage/var/www/html/$os_dir/x86_64/files/\"
rsync -av /mnt/source/Tools /mnt/sysimage/var/www/html/$os_dir/x86_64/files/

echo 'Configuring /etc/fstab to mount the ISO on boot.'
echo '/var/www/html/$os_dir/x86_64/iso/$iso_name	/var/www/html/$os_dir/x86_64/img	iso9660	loop	0 0' >> /mnt/sysimage/etc/fstab

echo 'Copying isolinux to /var/lib/tftpboot/boot/$os_dir/x86_64/'
rsync -av /mnt/source/isolinux/* /mnt/sysimage/var/lib/tftpboot/boot/$os_dir/x86_64/
# */ # Ignore me, I am unbreaking syntax highlighting in vim...
\%end


# Now it's time for the first chroot'ed configuration steps.
\%post --log=/tmp/post-install_chroot.log

$common_post

echo 'Writing out local yum repository config'
cat > /etc/yum.repos.d/striker0${number}.repo << EOF
[striker0${number}-$os_dir]
name=$striker_name 0${number} $os_dir v$say_ver + Custom Repository
baseurl=http://localhost/$os_dir/x86_64/img/
enabled=1
gpgcheck=0
priority=1
EOF

# Now setup the script for the user to call once booted.
echo 'Writing out the sample striker-installer script'
cat > /root/example_striker-installer.txt << EOF
# This is an example 'striker-installer' call. Feel free to edit this file
# here and then call it with 'sh /root/example_striker-installer.txt' to
# save typing all this out.
# 
# To understand what all these switches do, run './striker-installer --help' 
# and the help will be displayed.
# 
./striker-installer \\\\
 -b $my_bcn_ip/$bcn_netmask \\\\
 -i $my_ifn_ip/$ifn_netmask,dg=$ifn_gateway,dns1=$ifn_dns1,dns2=$ifn_dns2 \\\\
 -n \"${prefix}-striker0${number}.$domain\" \\\\
 -c \"$company_name\" \\\\
 -u \"$admin_user:$password\" \\\\
 --peer-dashboard hostname=${prefix}-striker0${peer_number}.$domain,bcn_ip=$peer_ip \\\\
 --router-mode \\\\
 -p $dhcp_range \\\\
";
		# Use '--rhn' on RHEL only.
		if ($distro eq "rhel")
		{
			$content .= " -d git \\\\
 --rhn \"rhn_$admin_user:rhn_$password\"
";
		}
		else
		{
			$content .= " -d git
";
		}
		$content .= "EOF


# This writes out the custom PXE menu used when installing nodes and dashboard
# from this system.
echo 'Writing out the default PXE menu'
cat > /var/lib/tftpboot/pxelinux.cfg/default << EOF
# Use the high-colour menu system.
UI vesamenu.c32
 
# Time out and use the default menu option. Defined as tenths of a second.
TIMEOUT 600
 
# Prompt the user. Set to '1' to automatically choose the default option. This
# is really meant for files matched to MAC addresses.
PROMPT 0
 
# Set the boot menu to be 1024x768 with a nice background image. Be careful to
# ensure that all your user's can see this resolution! Default is 640x480.
MENU RESOLUTION 1024 768

# The background image
MENU BACKGROUND $background
 
# These do not need to be set. I set them here to show how you can customize or
# localize your PXE server's dialogue.
MENU TITLE    $anvil_name Node and $striker_name Dashboard Install Server

# Below, the hash (#) character is replaced with the countdown timer. The
# '{,s}' allows for pluralizing a word and is used when the value is >= '2'.
MENU AUTOBOOT Will boot the next device as configured in your BIOS in # second{,s}.
MENU TABMSG   Press the <tab> key to edit the boot parameters of the highlighted option.
MENU NOTABMSG Editing of this option is disabled.
 
# The following options set the various colours used in the menu. All possible
# options are specified except for F# help options. The colour is expressed as
# two hex characters between '00' and 'ff' for alpha, red, green and blue
# respectively (#AARRGGBB).
# Format is: MENU COLOR <Item> <ANSI Seq.> <foreground> <background> <shadow type>
MENU COLOR screen      0  #80ffffff #00000000 std      # background colour not covered by the splash image
MENU COLOR border      0  #ffffffff #ee000000 std      # The wire-frame border
MENU COLOR title       0  #ffff3f7f #ee000000 std      # Menu title text
MENU COLOR sel         0  #ff00dfdf #ee000000 std      # Selected menu option
MENU COLOR hotsel      0  #ff7f7fff #ee000000 std      # The selected hotkey (set with ^ in MENU LABEL)
MENU COLOR unsel       0  #ffffffff #ee000000 std      # Unselected menu options
MENU COLOR hotkey      0  #ff7f7fff #ee000000 std      # Unselected hotkeys (set with ^ in MENU LABEL)
MENU COLOR tabmsg      0  #c07f7fff #00000000 std      # Tab text
MENU COLOR timeout_msg 0  #8000dfdf #00000000 std      # Timout text
MENU COLOR timeout     0  #c0ff3f7f #00000000 std      # Timout counter
MENU COLOR disabled    0  #807f7f7f #ee000000 std      # Disabled menu options, including SEPARATORs
MENU COLOR cmdmark     0  #c000ffff #ee000000 std      # Command line marker - The '> ' on the left when editing an option
MENU COLOR cmdline     0  #c0ffffff #ee000000 std      # Command line - The text being edited
# Options below haven't been tested, descriptions may be lacking.
MENU COLOR scrollbar   0  #407f7f7f #00000000 std      # Scroll bar
MENU COLOR pwdborder   0  #80ffffff #20ffffff std      # Password box wire-frame border
MENU COLOR pwdheader   0  #80ff8080 #20ffffff std      # Password box header
MENU COLOR pwdentry    0  #80ffffff #20ffffff std      # Password entry field
MENU COLOR help        0  #c0ffffff #00000000 std      # Help text, if set via 'TEXT HELP ... ENDTEXT'
 
### Now define the menu options

# It is safest to return booting to the client as the first and default option.
# This entry below will do just that.
LABEL next
	MENU LABEL ^A) Boot the next device as configured in your BIOS
	MENU DEFAULT
	localboot -1

LABEL pxe-new-node01
	MENU LABEL ^1) New $anvil_name Node 01 - $say_os v$say_ver - PXE - Deletes All Existing Data!
	TEXT HELP

		.------------------------------------------------------------------.
		| WARNING: This install will appear to stall at first! BE PATIENT! |
	        ^------------------------------------------------------------------^

	            To prevent traces of previous installs interrupting the 
		    Install Manifest run, this boot option starts by 'zeroing
		    out' the first 100 GiB of the drive. There is no output
		    while this runs.

		Installs a new $anvil_name Node 01 using $say_os v$say_ver. Will create a traditional 
		/boot + MBR install for systems with traditional BIOSes. Partition 
		will be 0.5 GiB /boot, 4 GiB <swap>, 40 GiB /.
	ENDTEXT
	KERNEL boot/$os_dir/x86_64/vmlinuz
	IPAPPEND 2
	APPEND initrd=boot/$os_dir/x86_64/initrd.img ks=http://$my_bcn_ip/$os_dir/x86_64/ks/pxe-new-node01.ks ksdevice=bootif

LABEL pxe-new-node02
	MENU LABEL ^2) New $anvil_name Node 02 - $say_os v$say_ver - PXE - Deletes All Existing Data!
	TEXT HELP

		.------------------------------------------------------------------.
		| WARNING: This install will appear to stall at first! BE PATIENT! |
	        ^------------------------------------------------------------------^

	            To prevent traces of previous installs interrupting the 
		    Install Manifest run, this boot option starts by 'zeroing
		    out' the first 100 GiB of the drive. There is no output
		    while this runs.

		Installs a new $anvil_name Node 02 using $say_os v$say_ver. Will create a traditional 
		/boot + MBR install for systems with traditional BIOSes. Partition 
		will be 0.5 GiB /boot, 4 GiB <swap>, 40 GiB /.
	ENDTEXT
	KERNEL boot/$os_dir/x86_64/vmlinuz
	IPAPPEND 2
	APPEND initrd=boot/$os_dir/x86_64/initrd.img ks=http://$my_bcn_ip/$os_dir/x86_64/ks/pxe-new-node02.ks ksdevice=bootif

LABEL pxe-new-striker01
	MENU LABEL ^3) New $striker_name 01 dashboard - $say_os v$say_ver - PXE - Deletes All Existing Data!
	TEXT HELP
	
		Installs a new $striker_name 01 using $say_os v$say_ver. Will create a traditional
		/boot + MBR install for systems with traditional BIOSes. Partition will 
		be 0.5 GiB /boot, 4 GiB <swap>, remainder for /.
	ENDTEXT
	KERNEL boot/$os_dir/x86_64/vmlinuz
	IPAPPEND 2
	APPEND initrd=boot/$os_dir/x86_64/initrd.img ks=http://$my_bcn_ip/$os_dir/x86_64/ks/pxe-new-striker01.ks ksdevice=bootif
	
LABEL pxe-new-striker02
	MENU LABEL ^4) New $striker_name 02 dashboard - $say_os v$say_ver - PXE - Deletes All Existing Data!
	TEXT HELP

		Installs a new $striker_name 02 using $say_os v$say_ver. Will create a traditional
		/boot + MBR install for systems with traditional BIOSes. Partition will 
		be 0.5 GiB /boot, 4 GiB <swap>, remainder for /.
	ENDTEXT
	KERNEL boot/$os_dir/x86_64/vmlinuz
	IPAPPEND 2
	APPEND initrd=boot/$os_dir/x86_64/initrd.img ks=http://$my_bcn_ip/$os_dir/x86_64/ks/pxe-new-striker02.ks ksdevice=bootif

label rescue
	MENU LABEL ^B) Rescue installed system
	TEXT HELP

		Boot the $say_os v$say_ver DVD in rescue mode.
	ENDTEXT
	KERNEL boot/$os_dir/x86_64/vmlinuz
	APPEND initrd=boot/$os_dir/x86_64/initrd.img rescue

label memtest86
	MENU LABEL ^C) Memory test
	TEXT HELP

		Test the RAM in the system for defects.
	ENDTEXT
	KERNEL memtest
	APPEND -
EOF

# Disable the libvirtd default bridge.
echo \"Disabling the default libvirtd bridge 'virbr0'.\"
cat /dev/null >/etc/libvirt/qemu/networks/default.xml

echo \"'chroot'ed post install script complete.\"
\%end


$copy_logs


### Script to setup partitions.
\%pre --log=/tmp/ks-preinstall.log

#!/bin/sh

# Prepare the disks in the script below. It checks '/proc/partitions' to see
# what configuration to use.

###############################################################################
# Creates a 512 MiB /boot, 4 GiB <swap> and the balance to /                  #
###############################################################################

# Default is to use /dev/sda. At this time, software arrays are not supported.
DRIVE=\"sda\";

# /dev/vda KVM virtual machine
if grep -q vda /proc/partitions; then
	DRIVE=\"vda\"
fi
";
		if ($target eq "usb")
		{
			$content .= "
### The USB drives comes up as 'sdb', so the Eee's HDD is /dev/sdc
# /dev/sdc ASUS EeeBox machine
if grep -q sdc /proc/partitions; then
	DRIVE=\"sdc\"
fi
";
		}
		else
		{
			$content .= "
# /dev/sdb ASUS EeeBox machine
if grep -q sdb /proc/partitions; then
	DRIVE=\"sdb\"
fi
";
		}

		$content .= "
# Now write the partition script
cat >> /tmp/part-include <<END
zerombr
clearpart --all --drives=\${DRIVE}
ignoredisk --only-use=\${DRIVE}
bootloader --location=mbr --driveorder=\${DRIVE}

part     /boot --fstype ext4 --size=512   --asprimary --ondisk=\${DRIVE}
part     swap  --fstype swap --size=4096  --asprimary --ondisk=\${DRIVE}
part     /     --fstype ext4 --size=100   --asprimary --ondisk=\${DRIVE} --grow

END

\%end
";
	}
	
	return($content);
}

# This returns the packages for either nodes or dashboards
sub get_packages
{
	my ($conf, $machine, $distro) = @_;

	my $striker_name = $conf->{sys}{striker_name};
	my $packages     = "# This is a very minimal installation. It is just enough to get the nodes ready
# for the Stage-2 'Install Manifest' run from the $striker_name dashboard.
\%packages
# We clobber the groups XML repodata, so we specify the packages directly.
# Core - mandatory
acl
attr
audit
basesystem
bash
coreutils
cpio
cronie
dhclient
e2fsprogs
filesystem
glibc
initscripts
iproute
iptables
iptables-ipv6
iputils
kbd
ncurses
openssh-server
passwd
policycoreutils
procps
redhat-support-tool
rhnsd
rootfiles
rpm
rsyslog
selinux-policy-targeted
setup
shadow-utils
subscription-manager
sudo
util-linux-ng
vim-minimal
yum
yum-rhn-plugin

# Core - Default
aic94xx-firmware
atmel-firmware
b43-openfwwf
bfa-firmware
efibootmgr
grub
ipw2100-firmware
ipw2200-firmware
ivtv-firmware
iwl100-firmware
iwl1000-firmware
iwl3945-firmware
iwl4965-firmware
iwl5000-firmware
iwl5150-firmware
iwl6000-firmware
iwl6000g2a-firmware
iwl6050-firmware
kernel-firmware
kexec-tools
libertas-usb8388-firmware
postfix
ql2100-firmware
ql2200-firmware
ql23xx-firmware
ql2400-firmware
ql2500-firmware
rt61pci-firmware
rt73usb-firmware
xorg-x11-drv-ati-firmware
zd1211-firmware

# Core - Optional
dracut-network

# Others - Common to nodes and dashboards
-kdump
alteeve-repo
gpm
perl
perl-Crypt-SSLeay
";
	if ($distro eq "centos")
	{
		$packages .= "yum-plugin-priorities\n";
	}
	
	if ($machine eq "striker")
	{
		$packages .= "
# Striker packages needed for 'striker-installer' to run
acpid
createrepo
gcc
glibc-devel
httpd 
perl-libwww-perl
rsync
screen 
syslinux 
syslinux-tftpboot
xinetd

### Needed to keep virt-manager from complaining.
augeas-libs
dnsmasq
ebtables
glusterfs
glusterfs-api
glusterfs-libs
gpxe-roms-qemu
iscsi-initiator-utils
keyutils
libgssglue
libtirpc
libevent
libvirt
lzop
netcf-libs
nfs-utils
nfs-utils-lib
numad
qemu-img
qemu-kvm
radvd
rpcbind
seabios
sgabios-bin
spice-server
vgabios
";
	}
	$packages .= "\%end\n";
	
	return($packages);
}

# This is common chroot'ed %post to all machines.
sub get_common_post
{
	my ($conf) = @_;
	
	my $common_post = "
# Tell the machine to save downloaded RPM updates (for possible distribution to
# other machines for low-bandwidth users). It also makes sure all NICs start on
# boot.
echo 'Configuring yum to keep its cache.'
sed -i 's/keepcache=0/keepcache=1/g' /etc/yum.conf

# Disable DNS lookup for SSH so that logins are quick when there is not Internet
# access.
echo 'Configuring sshd to not use DNS or GSSAPI authentication for fast logins without internet connections.'
sed -i 's/#UseDNS yes/UseDNS no/' /etc/ssh/sshd_config 
sed -i 's/#GSSAPIAuthentication no/GSSAPIAuthentication no/' /etc/ssh/sshd_config
sed -i 's/GSSAPIAuthentication yes/#GSSAPIAuthentication yes/' /etc/ssh/sshd_config

# Show details on boot.
echo 'Setting plymouth to use detailed boot screen'
plymouth-set-default-theme details --rebuild-initrd
sed -i 's/ rhgb//'  /boot/grub/grub.conf
sed -i 's/ quiet//' /boot/grub/grub.conf

# Setup 'list-ips', which will display the node's post-stage-1 IP address
# without the user having to log in.
echo /sbin/striker/list-ips >> /etc/rc.local
";
	
	return($common_post);
}

# This is the second non-chroot'ed %post that copies the install logs to /root/
sub get_copy_logs
{
	my ($conf) = @_;
	
	my $copy_logs = "
# This is set to run at the end. It copies all of the kickstart logs into the
# root user's home page.
\%post --nochroot
echo 'Copying all the anaconda related log files to /root/install/'

if [ ! -e '/mnt/sysimage/root/install' ]
then
	mkdir /mnt/sysimage/root/install
fi
cp -p /tmp/nochroot*   /mnt/sysimage/root/install/
cp -p /tmp/kernel*     /mnt/sysimage/root/install/
cp -p /tmp/anaconda*   /mnt/sysimage/root/install/
cp -p /tmp/ks*         /mnt/sysimage/root/install/
cp -p /tmp/program.log /mnt/sysimage/root/install/
cp -p /tmp/storage*    /mnt/sysimage/root/install/
cp -p /tmp/yum.log     /mnt/sysimage/root/install/
cp -p /tmp/ifcfg*      /mnt/sysimage/root/install/
cp -p /tmp/syslog      /mnt/sysimage/root/install/
\%end
";

	return($copy_logs);
}

sub get_date
{
	my ($conf, $time) = @_;
	$time = time if not defined $time;
	
	my @time   = localtime($time);
	my $year   = ($time[5] + 1900);
	my $month  = sprintf("%.2d", ($time[4] + 1));
	my $day    = sprintf("%.2d", $time[3]);
	my $hour   = sprintf("%.2d", $time[2]);
	my $minute = sprintf("%.2d", $time[1]);
	my $second = sprintf("%.2d", $time[0]);
	
	# this returns "yyyy-mm-dd_hh:mm:ss".
	my $date = "$year-$month-$day $hour:$minute:$second";
	
	return ($date);
}

exit(0);
